### PR TITLE
Enable installation as submodule

### LINKED ISSUE #74: Install as git submodule
Hi

Are you planning to make this plugin installable as a git submodule like other Kirby plugins do?

The way I've got my multisite folders and git repos set up it would be great if I could do that with this plugin too.

Many thanks :)

### PR DESCRIPTION
**Pull request by CHE1RON**
Hey there,
this commit fixes #74, closely following the [official sources](https://getkirby.com/docs/guide/plugins/plugin-setup-composer) on plugins supporting manual installation (ZIP folder, submodule, ..)

Cheers,
Martin

### CODE REVIEW

**Comment by thathoff** [comment]
Thank you for your pull request. The reason this has not been done yet is that we now include dependencies in the plugin and I’m not sure if I want to be responsible for keeping those dependencies up to date.

To better understand your setup: What is the reason you are using git submodules and don’t install directly via composer? That might be very handy to know and understand the need for supporting this. Thank you!

**Comment by CHE1RON** [comment]
Hey there @thathoff 
I'm never ever using submodules in my projects, but I know people who do - furthermore, some devs and even non-tech folks like to download ZIP files, unpack them and give plugins a try first - again, not me, I'm a Composer guy - but nonetheless in my plugins I always include these dependencies.

Thing is: the few people going down the ZIP/submodule route never complained about dependencies, everyone else using Composer does not bother either way 😉

**Comment by thathoff** [comment]
Thank you. Nevertheless I will still be responsible for keeping the dependencies up to date. To support basic zip installation I’ve added [this section](https://github.com/thathoff/kirby-git-content#download-and-configure-the-plugin) to the readme. But yeah I totally understand your point. As this is a plugin for the more technically advanced people I thought it’s ok to just support the composer installation. But I might change my opinion on this ;)

**Comment by CHE1RON** [comment]
Right, thanks for your feedback! I saw the issue and just went from there actually 😅

**Comment by mlbiche** [comment]
Hi :wave: Is there any move expected/planned on this PR ?

**Comment by thathoff** [comment]
I’ve not made a decision if we should include the dependencies here. To get a better understanding on how the plugin is uses: Can you explain how you run your setup that you need this and eg. cannot use composer or [the way described in the readme](https://github.com/thathoff/kirby-git-content#download-and-configure-the-plugin)?

Thank you!

**Comment by CHE1RON** [comment]
(On a side note: Every single one of my plugins using Composer includes its dependencies so people may simply download & test them ..)

**Comment by thathoff** [comment]
Yeah, but in our case we use composer requirements to also restrict the installation to working Kirby versions which results in a complete Kirby copy inside the vendor folder inside the repository which is also not a good idea. 

I saw other plugins solving this by defining Kirby versions as dev dependency. Maybe that’s a way to go…

**Comment by thathoff** [comment]
Cherry picked into the [5.1.0 Release Branch](https://github.com/thathoff/kirby-git-content/pull/101)  so im closing this here. Thank you!

**Comment by CHE1RON** [comment]
Thanks for this plugin, happy to help anytime 😉

**Pull request closed without merging**
