### PR TITLE
Release Version 4

### PR DESCRIPTION
**Pull request by thathoff**
## Features
- finalize Maintainer switch
- finalize rename to GitContent
- Allow POST request to webhooks (thanks to @graphichavoc)
- Install into plugins folder (thanks to @s3ththompson)
- Switch to `coyl/git` PHP git library
- allow configuration of commit message (thanks to @JonasDoebertin)

## BREAKING CHANGES:
- Name Changed to Git Content
- Config options changed (`blankogmbh.gcapc` to `thathoff.git-content`)
- Webhook-URLS changed: `/gcapc/(push|pull)` changed to `/git-content/(push|pull)

### CODE REVIEW

**Comment by s3ththompson** [comment]
any blockers before releasing this? @thathoff

**Comment by thathoff** [comment]
Thanks for asking, no, no blockers. I kept the new version running on some projects for a couple of weeks to test everything. Seems to work fine. I think I’ll release v4 in the next couple of days.

**Comment by l4ci** [comment]
Any news here @thathoff ?

**Comment by thathoff** [comment]
Sorry for the delay. There is still a bug which prevents pushing in some cases. But I'm planning to release v4 today when this bug is fixed.

Thanks for your patience.

**Pull request merged**
